config/routes.rb
Rails.application.routes.draw do
  get 'work' => 'static_pages#work'

  get 'about' => 'static_pages#about'

  get 'contact' => 'contacts#new'


  resources :contacts, only: [:new, :create]

  root 'static_pages#home'








end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name, validate => true
	attribute :email, validate => /\A([\w\.%\+\-])@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message, validate => true
	attribute :nickname, validate => true

	def headers 
		{
			:subject => "Contact Form",
			:to => "daini5050@live.com",
			:from => %("#{name}" <#{email}>)
		}
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = "Cannot send message, please try again."
			render :new
		end
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def work
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
		base_title = "Daini Sani"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end

	def copyright_notice_year_range(start_year)
	  # In case the input was not a number (nil.to_i will return a 0)
	  start_year = start_year.to_i

	  # Get the current year from the system
	  current_year = Time.new.year

	  # When the current year is more recent than the start year, return a string 
	  # of a range (e.g., 2010 - 2012). Alternatively, as long as the start year 
	  # is reasonable, return it as a string. Otherwise, return the current year 
	  # from the system.
	  if current_year > start_year && start_year > 2000
	    "#{start_year} - #{current_year}"
	  elsif start_year > 2000
	    "#{start_year}"
	  else
	    "#{current_year}"
	  end
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/create.html.erb
<% provide(:title, "Thanks") %>
<div class="contact-bg">
	<div class="wrapper">
		<header class="header clearfix">
			<h1 class="logo">
				<%= link_to 'Daini Sani', root_path, class: 'nav-links' %>
			</h1>
			<nav>
				<%= link_to 'Home', root_path, class: 'nav-links' %> 
				<%= link_to 'About', about_path, class: 'nav-links' %>
				<%= link_to 'Work', work_path, class: 'nav-links' %>
				<%= link_to 'Contact', contact_path, class: 'nav-links active' %>
			</nav>	
		</header>
	</div>
</div>
<main class="wrapper">
	<div class="row">
		<div class="col-12">
			<h2 class="contact-title">Thanks you for your message!</h2>
			<p class="details-tilte">I'll get back to you soon.</p>
		</div>
	</div>
	<hr>
</main>

app/views/contacts/new.html.erb
<% provide(:title, "Contact") %>
<div class="contact-bg">
	<div class="wrapper">
		<header class="header clearfix">
			<h1 class="logo">
				<%= link_to 'Daini Sani', root_path, class: 'nav-links' %>
			</h1>
			<nav>
				<%= link_to 'Home', root_path, class: 'nav-links' %> 
				<%= link_to 'About', about_path, class: 'nav-links' %>
				<%= link_to 'Work', work_path, class: 'nav-links' %>
				<%= link_to 'Contact', contact_path, class: 'nav-links active' %>
			</nav>	
		</header>
	</div>
</div>
<main class="wrapper">
	<div class="row">
		<div class="col-12">
			<h2 class="contact-title">Thanks for getting in touch!</h2>
			<h3 class="details-tilte">I'd like to talk to you. Just tell me a few things</h3>
		</div>
	</div>
	<br>
	<hr class="pad-bottom">
	<div class="row">
		<div class="col-12 form-wrapper">
			<%= form_for @contact do |f| %>
				<%= f.label :name %><br>
				<%= f.text_field :name, required: true %>

				<br>

				<%= f.label :email %><br>
				<%= f.email_field :email, required: true %>

				<br>

				<%= f.label :message %><br>
				<%= f.text_area :message, as: :text %><br>

				<div class="hidden">
					<%= f.label :nickname %><br>
					<%= f.text_field :nickname, hint: "leave this field blank" %>
				</div>

				<%= f.submit "Send message", class: "btn" %>
			<% end %>
		</div>
	</div>
</main>

app/views/layouts/_footer.html.erb
<footer class="row">
	<main class="wrapper">
		 <div class="row clearfix">
		 	<div class="col-7 clearfix footer-nav">
		 		<nav>
		 			<h5 class="get-in-touch">Daini Sani</h5>
		 			<ul>
						<li><%= link_to 'Home', root_path, class: 'nav-links' %></li> 
						<li><%= link_to 'About', about_path, class: 'nav-links' %></li>
						<li><%= link_to 'Work', work_path, class: 'nav-links active' %></li>
						<li><%= link_to 'Contact', contact_path, class: 'nav-links' %></li>
					</ul>
				</nav>
				<div class="address">
                    <h5 class="hit-me-up">Get In Touch</h5>
                    <address>Salamis Road<br>
                        Famagusta, TRNC.<br>
                        <a href="tel:+905338795437"><i class="fa fa-phone"></i> +905338794537</a><br>
                        <a href="mailto:daini5050@live.com"><i class="fa fa-envelope"></i> daini5050@live.com</a>
                    </address>
                </div>
		 	</div>
		 	<div class="col-5 footer-nav-right">
		 		<input id="flip" type="checkbox" name="flip-card">
                    <label for="flip">
                        <div class="card">
                            <div class="front">
                                <div class="front_bg">
                                    DS
                                </div>
                                <div class="strip"></div>
                                <div class="left_side"></div>
                                <div class="right_side"></div>
                                <div class="name">
                                    <span>DAINI</span> SANI
                                </div>
                                <div class="profession">
                                    Web Developer
                                </div>
                            </div>
                            <div class="back">
                                <div class="left_back"></div>
                                <div class="item">
                                    <a href="https://github.com/daini5050" target="_blank"><i class="fa fa-github card-icon"></i>Github</a>
                                </div>
                                <div class="item">
                                    <a href="https://www.facebook.com/daini.sani" target="_blank"><i class="fa fa-facebook card-icon"></i>Facebook</a>
                                </div>
                                <div class="item">
                                    <a href="http://codepen.io/daini5050" target="_blank"><i class="fa fa-codepen card-icon"></i>Codepen</a>
                                </div>
                                <div class="item">
                                    <a href="https://twitter.com/daini5050" target="_blank"><i class="fa fa-twitter card-icon"></i>Twitter</a>
                                </div>
                            </div>
                        </div>
                    </label>
		 	</div>
	 </div>
	 <hr>
	 <div class="row">
	 	<div class="col-12 social">
	 		<a href="https://facebook.com/daini.sani" class="social-links" target="_blank"><i class="fa fa-facebook"></i>facebook</a>
	 		<a href="https://github.com/daini5050" class="social-links" target="_blank"><i class="fa fa-github"></i> github</a>
	 		<a href="https://codepen.io/daini5050" class="social-links" target="_blank"><i class="fa fa-codepen"></i> codepen</a>
	 		<a href="https://twitter.com/daini5050" class="social-links" target="_blank"><i class="fa fa-twitter"></i> twitter</a>
	 	</div>
		<div class="col-12">
		 	<small>&copy; Daini Sani <%= copyright_notice_year_range(2016) %> All rights reserverd.</small>
		</div>
	 </div>
 	</main>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">	
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= full_title(yield(:title)) %></title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container" id="box">
	<%= yield %>
	<%= render 'layouts/footer' %>
	
	</div>
</body>
</html>

app/views/static_pages/_header.html.erb
<header class="header clearfix">
			
	<h1 class="logo">
		<%= link_to 'Daini Sani', root_path, class: 'nav-links' %>
	</h1>
	<nav>
		<%= link_to 'Home', root_path, class: 'nav-links' %> 
		<%= link_to 'About', about_path, class: 'nav-links' %>
		<%= link_to 'Work', work_path, class: 'nav-links active' %>
		<%= link_to 'Contact', contact_path, class: 'nav-links' %>
	</nav>	
</header>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="contact-bg">
	<div class="wrapper">
		<header class="header clearfix">
			<h1 class="logo">
				<%= link_to 'Daini Sani', root_path, class: 'nav-links' %>
			</h1>
			<nav>
				<%= link_to 'Home', root_path, class: 'nav-links' %> 
				<%= link_to 'About', about_path, class: 'nav-links active' %>
				<%= link_to 'Work', work_path, class: 'nav-links' %>
				<%= link_to 'Contact', contact_path, class: 'nav-links' %>
			</nav>	
		</header>
	</div>
</div>
<main class="wrapper">
	<div class="row clearfix abt-page">
		<div class="col-2 abt-pg-content abt-pa-content-left">
			<img src="/assets/me4.JPG" class="img-me" alt="image of Daini Sani">
		</div>
		<div class="col-10 abt-pg-content abt-pg-content-right">
			<h2 class="contact-title">About</h2>
			<p class="details-tilte">
				My name is Daini Sani. I'm an Electrical Engineer by academics and a  self taught web developer. I became passionate about web development after unwittinly sitting in a class of Javascript instead of communication systems. Thank God that happened...now i couldn't think of anything i'm more ardent about. Below are some of the skills that i've acquired over the process of teaching myself how to code and because i find the field of web development really exciting, i'm always excited to learn new skills. 
			</p>
			<h3>Languages</h3>
			<hr>
			<br>
			<ul>
				<li>XHTML / HTML5 &nbsp; <b>(Expert)</b></li>
				<li>CSS / CSS3 &nbsp; <b>(Expert)</b></li>
				<li>Javascript + JSON / AJAX &nbsp; <strong>(Intermediate</strong>)</li>
				<li>Ruby &nbsp; <b>(Intermediate)</b></li>
				<li>C/C++ &nbsp; <b>(Beginner)</b></li>
			</ul>
			<h3>Libraries / Frameworks</h3>
			<hr>
			<br>
			<ul>
				<li>Ruby on Rails &nbsp; <b>(Intermediate)</b></li>
				<li>Jquery &nbsp; <b>(Intermediate)</b></li>
				<li>React &nbsp; <b>(Beginner)</b></li>
				<li>Angular &nbsp; <b>(Beginner)</b></li>
				<li>Bootstrap &nbsp; <b>(Intermediate)</b></li>
			</ul>
			<h3>Utilities</h3>
			<hr>
			<br>
			<ul>
				<li>NPM &nbsp; <b>(Intermediate)</b></li>
				<li>Gulp &nbsp; <b>(Intermediate)</b></li>
				<li>Bower &nbsp; <b>(Intermediate)</b></li>
			</ul>
			<h3>Tools</h3>
			<hr>
			<br>
			<ul>
				<li>Git / Github &nbsp; <b>(Intermediate)</b></li>
				<li>SASS &nbsp; <b>(Intermediate)</b></li>
				<li>Chrome Developer Tool &nbsp; <b>(Expert)</b></li>
				<li>Command Line &nbsp; <b>(Intermediate)</b></li>
			</ul>
		</div>
	</div>
	<br>
	<hr class="pad-bottom">
</main>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="contact-bg">
	<div class="wrapper">
		<header class="header clearfix">
			<h1 class="logo">
			</h1>
			<div class="navicon"><i class="fa fa-bars"></i></div>
			<nav>
				<%= link_to 'Home', root_path, class: 'nav-links' %> 
				<%= link_to 'About', about_path, class: 'nav-links' %>
				<%= link_to 'Work', work_path, class: 'nav-links' %>
				<%= link_to 'Contact', new_contact_path, class: 'nav-links active' %>
			</nav>	
		</header>
	</div>
</div>
<main class="wrapper">
	<div class="row">
		<div class="col-12">
			<h2 class="contact-title">Thanks for getting in touch!</h2>
			<h3 class="details-tilte">I'd like to talk to you. Just tell me a few things</h3>
		</div>
	</div>
</main>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="main">
	<div class="wrapper">
		<header class="header clearfix">
			<h1 class="logo">
				<%= link_to 'Daini Sani', root_path, class: 'nav-links' %>
			</h1>
			<nav class="clearfix">
					<%= link_to 'Home', root_path, class: 'nav-links active' %> 
					<%= link_to 'About', about_path, class: 'nav-links' %>
					<%= link_to 'Work', work_path, class: 'nav-links' %>
					<%= link_to 'Contact', contact_path, class: 'nav-links' %>
			</nav>	
		</header>
		<span>
			<h2>
				Hi, I'm Daini Sani.
			</h2>
		</span>
		<span>
			<h3>
				Front-end &amp; Ruby on Rails developer.
			</h3>
		</span>
		<div class="intro">
		<p id="typer" class="writer">
            I enjoy building everything from small business sites to rich interactive web apps. <br>If you are a business seeking a web presence or an employer looking to hire, <br>you can get in touch with me here.
        </p>
		</div>
		<div class="action">
			<%= link_to "Get Started", contact_path, class: "learn-btn" %>
			<a href="/assets/resume.pdf" target="_blank" download="resume.pdf" class="learn-btn hire-btn" >Hire Me</a>
		</div>
	</div>
</div>
<main class="wrapper row">
	<h3 class=work-title>Here are some of my latest work.</h3>
	<div class="row clearfix first">
      <div class="item-1 item">
        <a href="http://codepen.io/daini5050/full/GorMJr/">
			<img src="/assets/1.jpg" class="attachment-work size-work wp-post-image" alt="gigya_featured">
			<div class="details">
				<h2 class="portfolio-piece-title">FreeCodeCamp</h2>
				<p>Camper News Blog</p>
			</div>
		</a>
      </div>
      <div class="item-2 item">
        <a href="#">
			<img src="/assets/2.jpg" class="attachment-work size-work wp-post-image" alt="gigya_featured">
			<div class="details">
				<h2 class="portfolio-piece-title">Placeholder Image</h2>
				<p>Defining the Future of Marketing</p>
			</div>
		</a>
      </div>
      <div class="item-3 item">
        <a href="#">
			<img src="/assets/c2.jpg" class="attachment-work size-work wp-post-image" alt="gigya_featured">
			<div class="details">
				<h2 class="portfolio-piece-title">Placeholder Image</h2>
				<p>Defining the Future of Marketing</p>
			</div>
		</a>
      </div>
	</div>
	<div class="row clearfix first">
		<div class="item-1 item">
        <a href="#">
			<img src="/assets/c3.jpg" class="attachment-work size-work wp-post-image" alt="gigya_featured">
			<div class="details">
				<h2 class="portfolio-piece-title">Placeholder Image</h2>
				<p>Defining the Future of Marketing</p>
			</div>
		</a>
      </div>
      <div class="item-2 item">
        <a href="#">
			<img src="/assets/3.jpg" class="attachment-work size-work wp-post-image" alt="gigya_featured">
			<div class="details">
				<h2 class="portfolio-piece-title">Placeholder Image</h2>
				<p>Defining the Future of Marketing</p>
			</div>
		</a>
      </div>
      <div class="item-3 item">
        <a href="#">
			<img src="/assets/4.jpg" class="attachment-work size-work wp-post-image" alt="gigya_featured">
			<div class="details">
				<h2 class="portfolio-piece-title">Placeholder Image</h2>
				<p>Defining the Future of Marketing</p>
			</div>
		</a>
      </div>
	</div>
	<div class="row clearfix">
		<div class="item-1 item">
        <a href="#">
			<img src="/assets/5.jpg" class="attachment-work size-work wp-post-image" alt="gigya_featured">
			<div class="details">
				<h2 class="portfolio-piece-title">Placeholder Image</h2>
				<p>Defining the Future of Marketing</p>
			</div>
		</a>
      </div>
      <div class="item-2 item">
        <a href="#">
			<img src="/assets/6.jpg" class="attachment-work size-work wp-post-image" alt="gigya_featured">
			<div class="details">
				<h2 class="portfolio-piece-title">Placeholder Image</h2>
				<p>Defining the Future of Marketing</p>
			</div>
		</a>
      </div>
      <div class="item-3 item">
        <a href="#">
			<img src="/assets/7.jpg" class="attachment-work size-work wp-post-image" alt="gigya_featured">
			<div class="details">
				<h2 class="portfolio-piece-title">Placeholder Image</h2>
				<p>Defining the Future of Marketing</p>
			</div>
		</a>
      </div>
	</div>
	<section class="row">
		<div class="col-12">
			<h2 class=testimonials>What clients are saying...</h2>
		</div>
		<div class="row">
			<div class="col-12 slider">
				<input type="radio" id="slide_text" checked name="slide-switches" class="slide-switch">
				<label for="slide_text" class="slide-label">Slide text</label>
				<div class="slide-content padded">
					<blockquote>
						The collaboration we had was as good as the final product. I'm astounded by the quality of work they produced. Their work has the power to change your business. Can't wait to work with them again.
                        <cite><%= image_tag("clinet-5.jpg", alt: "image for client-5") %>Jordan Ash</cite>
					</blockquote>
				</div>
				<input type="radio" id="slide_texts" checked name="slide-switches" class="slide-switch">  
                    <label for="slide_texts" class="slide-label">Slide Text</label>
                    <div class="slide-content padded">
                        <blockquote>
                            I can be sometimes difficult to work with, but seeing how this guy listened to me and made vital suggestions tells me how good he is. At the end of the day, great design, great turn-around and great result.
                            <cite><%= image_tag("clinet-1.jpg", alt: "image for client-1") %>Ashley Smith</cite>
                        </blockquote>
                    </div>
                    <input type="radio" id="slide_textss" checked name="slide-switches" class="slide-switch">  
                    <label for="slide_textss" class="slide-label">Slide Text</label>
                    <div class="slide-content padded">
                        <blockquote>
                            When i need a beautiful and yet fully functional site or app, i come to Daini Dev. Anything Daini and his team touch turns into smooth, intuitive, GUI goodness. They make delightful products. It's really that simple.
                            <cite><%= image_tag("clinet-7.jpg", alt: "image for client-7") %>Wesley Grant</cite>
                        </blockquote>
                    </div>
			</div>
		</div>
	</section>
</main>

app/views/static_pages/work.html.erb
<% provide(:title, "Work") %>
<div class="contact-bg">
	<div class="wrapper">
		<header class="header clearfix">
			<h1 class="logo">
				<%= link_to 'Daini Sani', root_path, class: 'nav-links' %>
			</h1>
			<nav>
				<%= link_to 'Home', root_path, class: 'nav-links' %> 
				<%= link_to 'About', about_path, class: 'nav-links' %>
				<%= link_to 'Work', work_path, class: 'nav-links active' %>
				<%= link_to 'Contact', new_contact_path, class: 'nav-links' %>
			</nav>	
		</header>
	</div>
</div>
<main class="wrapper">
	<h2 class="work-title">Details of projects will go here.</h2>
</main>